# Generated by Django 4.0.10 on 2023-03-07 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(db_index=True, max_length=20)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserForcing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tg_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stats.tguser')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
